# Usar Node.js 20
FROM node:20

# Crear directorio
WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto del frontend
EXPOSE 3000

# Comando de arranque
CMD ["npm", "start"]
