version: "3.9"

services:
  backend:
    build: ./app/backend
    ports:
      - "6000:5000"
    volumes:
      - ./app/backend:/app
    working_dir: /app
    command: npm start
    networks:
      - mi_red
    environment:
      - DB_HOST=db   # 👈 nombre del contenedor de la DB
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mydb

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    networks:
      - mi_red
    environment:
      - REACT_APP_API_URL=http://backend:5000

networks:
  mi_red:
    external: true   # 👈 porque la red ya existe y la usas en varios compose