FROM jenkins/jenkins:jdk21

USER root
# Permitir que Jenkins use Docker
RUN usermod -aG docker jenkins
# Instala Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Instala docker-compose usando pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install docker-compose && \
    rm -rf /var/lib/apt/lists/*
    
USER jenkins

EXPOSE 8080