FROM jenkins/jenkins:jdk21

USER root
# Permitir que Jenkins use Docker
RUN usermod -aG docker jenkins

# Instala Docker CLI y dependencias para docker-compose
RUN apt-get update && \
    apt-get install -y docker.io curl python3 python3-pip && \
    pip3 install docker-compose && \
    rm -rf /var/lib/apt/lists/*
    
USER jenkins

EXPOSE 8080