pipeline {
    agent {
        docker {
            image 'node:20'  // o la versión que necesites
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        BACKEND_IMAGE = "mi_backend:latest"
        FRONTEND_IMAGE = "mi_frontend:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/kexev5-dev/ProjectFinal-IaC.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'npm install'
                    sh 'npm test || echo "Tests fallidos pero continuamos"'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy Backend y Frontend') {
            agent any  // 👈 Esto fuerza que se ejecute en Jenkins, no en node:20
            steps {
                sh '''
                  echo "Levantando servicios con Docker Compose..."
                  docker compose down
                  docker compose up -d --build
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline finalizado correctamente. Backend y Frontend actualizados!'
        }
        failure {
            echo 'Algo falló en el pipeline. Revisa los logs!'
        }
        always {
            echo 'Pipeline terminado.'
        }
    }
}
